CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "system_role" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "Project" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "ProjectUser" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "project_id" int,
  "project_role" varchar
);

CREATE TABLE "IssueType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE "Status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "system_level" boolean,
  "created_at" timestamp
);

CREATE TABLE "Workflow" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "issue_type_id" int
);

CREATE TABLE "WorkflowStep" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workflow_id" int,
  "status_id" int,
  "is_initial" boolean,
  "is_final" boolean
);

CREATE TABLE "WorkflowTransition" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from_step_id" int,
  "to_step_id" int
);

CREATE TABLE "Ticket" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "issue_type_id" int,
  "summary" varchar,
  "due_date" date,
  "assignee_id" int,
  "reporter_id" int,
  "status_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "Comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "user_id" int,
  "content" text,
  "created_at" timestamp
);

CREATE TABLE "Attachment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "filename" varchar,
  "path" varchar,
  "uploaded_by" int,
  "uploaded_at" timestamp
);

CREATE TABLE "CustomFieldDefinition" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "field_type" varchar,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE "ProjectCustomField" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "custom_field_id" int,
  "issue_type_id" int
);

CREATE TABLE "TicketCustomFieldValue" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "custom_field_id" int,
  "value_string" varchar,
  "value_number" numeric,
  "value_date" date
);

CREATE TABLE "TicketLinkType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "name" varchar,
  "directionality" varchar
);

CREATE TABLE "TicketLink" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_ticket_id" int,
  "target_ticket_id" int,
  "link_type_id" int
);

CREATE TABLE "AuditLog" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" timestamp,
  "user_id" int,
  "action" varchar,
  "entity" varchar,
  "entity_id" int,
  "before" json,
  "after" json
);

ALTER TABLE "ProjectUser" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "ProjectUser" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("id");

ALTER TABLE "IssueType" ADD FOREIGN KEY ("created_by") REFERENCES "User" ("id");

ALTER TABLE "Workflow" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("id");

ALTER TABLE "Workflow" ADD FOREIGN KEY ("issue_type_id") REFERENCES "IssueType" ("id");

ALTER TABLE "WorkflowStep" ADD FOREIGN KEY ("workflow_id") REFERENCES "Workflow" ("id");

ALTER TABLE "WorkflowStep" ADD FOREIGN KEY ("status_id") REFERENCES "Status" ("id");

ALTER TABLE "WorkflowTransition" ADD FOREIGN KEY ("from_step_id") REFERENCES "WorkflowStep" ("id");

ALTER TABLE "WorkflowTransition" ADD FOREIGN KEY ("to_step_id") REFERENCES "WorkflowStep" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("issue_type_id") REFERENCES "IssueType" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("assignee_id") REFERENCES "User" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("reporter_id") REFERENCES "User" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("status_id") REFERENCES "Status" ("id");

ALTER TABLE "Comment" ADD FOREIGN KEY ("ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "Comment" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Attachment" ADD FOREIGN KEY ("ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "Attachment" ADD FOREIGN KEY ("uploaded_by") REFERENCES "User" ("id");

ALTER TABLE "CustomFieldDefinition" ADD FOREIGN KEY ("created_by") REFERENCES "User" ("id");

ALTER TABLE "ProjectCustomField" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("id");

ALTER TABLE "ProjectCustomField" ADD FOREIGN KEY ("custom_field_id") REFERENCES "CustomFieldDefinition" ("id");

ALTER TABLE "ProjectCustomField" ADD FOREIGN KEY ("issue_type_id") REFERENCES "IssueType" ("id");

ALTER TABLE "TicketCustomFieldValue" ADD FOREIGN KEY ("ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "TicketCustomFieldValue" ADD FOREIGN KEY ("custom_field_id") REFERENCES "CustomFieldDefinition" ("id");

ALTER TABLE "TicketLinkType" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("id");

ALTER TABLE "TicketLink" ADD FOREIGN KEY ("source_ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "TicketLink" ADD FOREIGN KEY ("target_ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "TicketLink" ADD FOREIGN KEY ("link_type_id") REFERENCES "TicketLinkType" ("id");

ALTER TABLE "AuditLog" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");
